version: "3.9"

services:
  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - ./src:/var/www/html
    ports:
      - "9000:9000"

  nginx:
    image: nginx:1.18
    container_name: nginx
    ports:
      - '8000:80'
    depends_on:
      - php
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/html/

  mysql:
    build:
      context: ./docker/mysql
      dockerfile: Dockerfile
    container_name: mysql
    ports:
      - '4306:3306'
    environment:
      MYSQL_DATABASE: syi
      MYSQL_USER: syi_laravel
      MYSQL_PASSWORD: syi_laravel
      MYSQL_ROOT_PASSWORD: root
      TZ: 'Asia/Tokyo'
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/my_conf:/etc/mysql/conf.d:ro

  db-test:
    image: mysql:8.0
    container_name: db-test
    environment:
      MYSQL_DATABASE: syi_db_test
      MYSQL_USER: syi_test
      MYSQL_PASSWORD: syi_test
      MYSQL_ROOT_PASSWORD: root
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./docker/db-test/data:/var/lib/mysql
      - ./docker/db-test/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/db-test/sql:/docker-entrypoint-initdb.d
    ports:
      - 3000:3306
